########################
# Get input Excel file #
########################

args <- commandArgs(trailingOnly=TRUE)
ExcelFile <- args[1]
if (!grepl("\\.xlsx?$",ExcelFile)){
   sink("stderr.txt")
   cat("ERROR: The input file must have a name ending with .xlsx or .xls\n")
   quit(save="no",status=1,runLast=FALSE)
}

ZipFile <- args[2]
if (!grepl("\\.zip$",ZipFile)){
  sink("stderr.txt")
  cat("ERROR: The input file must have a name ending with .zip\n")
  quit(save="no",status=1,runLast=FALSE)
}

###################
# Set Environment #
###################

# libraries needed
library("readr")
library("gdata")
library("methods")
library("openxlsx")

# remove STANDARD ERROR generated by "library(gdata)"
system("rm stderr.txt")

##################
# Reformat Input #
##################

# read arguments and check correct format
SampleInfo <- as.matrix(read.xls(ExcelFile,sheet=1,colClasses="character"))
if (sum(c("SAMPLE","DESIRED.PERCENTAGE.RUN1.RUN2","RUN1.VOLUME","RUN1.BS.PERCENTAGE","TOTAL.VOLUME.POOL1","pM.POOL1", "pM.POOL2")==colnames(SampleInfo))!=7){
   sink("stderr.txt")
   print("ERROR: Colnames of Excel should be SAMPLE, DESIRED PERCENTAGE RUN1+RUN2, RUN1 VOLUME, RUN1 BS PERCENTAGE, TOTAL VOLUME POOL1, pM POOL1, pM POOL2 !")
   quit(save="no",status=1,runLast=FALSE)
}
if (nrow(SampleInfo)<2){
   sink("stderr.txt")
   print(paste("ERROR: Could find only ",nrow(SampleInfo)," rows in the Excel?? A repooling makes sense only with at least 2 libraries.",sep=""))
   quit(save="no",status=1,runLast=FALSE)
}
bSelect <- SampleInfo[,1]!=""
SampleInfo <- SampleInfo[bSelect,]

# extract variable values
samples <- SampleInfo[,1]
percentages_combined <- as.numeric(SampleInfo[,2])
names(percentages_combined) <- samples
if (sum(percentages_combined)!=100){
        #print(paste("ERROR: Desired percentage run1+run2 should add up to 100, while we see that the sum is ",sum(percentages_combined)," !",sep=""))
        #return(0)
  sink("stdout.txt")
  print(paste("WARNING: Desired percentage run1+run2 should add up to 100, while we see that the sum is ",sum(percentages_combined)," ! We have rescaled the percentages to get to 100.",sep=""))
  sink()
  scaling <- 100/sum(percentages_combined)
  percentages_combined <- scaling*percentages_combined
}
volumes_Run1 <- as.numeric(SampleInfo[,3])
names(volumes_Run1) <- samples
percentages_Run1 <- as.numeric(SampleInfo[,4])
names(percentages_Run1) <- samples
volume_pool1 <- as.numeric(SampleInfo[1,5])
pM_pool1 <- as.numeric(SampleInfo[1,6])
pM_pool2 <- as.numeric(SampleInfo[1,7])
extra_seq <- pM_pool2/pM_pool1

###############
# Computation #
###############

# Step 1: determine desired percentages for each sample in pool 2
RUN1 <- 100*percentages_Run1/sum(percentages_Run1) # BS does not include undetermined reads in the percentages, so the total sum does not add up to 100%
nsamps_pool1 <- length(percentages_Run1)
RUN2_TMP <- sapply(((percentages_combined*(1+extra_seq))-RUN1)/extra_seq,max,0) # first estimate of the desired percentages. if a sample had so much reads in run 1 that no additional reads are required, do not include that sample in pool 2
bInclude <- as.numeric(RUN2_TMP>0);
TMP <- RUN1*bInclude; tmp <- sum(bInclude*percentages_combined)
percentages_combined <- 100* bInclude*percentages_combined/tmp # recalculate the desired percentages of reads, when only looking at reads for included samples
RUN2 <- bInclude*((percentages_combined*((extra_seq*100)+sum(TMP))/100)-RUN1)/(extra_seq*100) # desired fractions (not percentages) for each sample in pool 2

# Step 2: compute volume factors to get the desired percentages
M <- matrix(0,nrow=nsamps_pool1,ncol=nsamps_pool1)
colnames(M) <- rownames(M) <- samples
for (i in 1:nsamps_pool1){
        ROW <- -RUN1 * (RUN2[i]/((1-RUN2[i])*RUN1[i]))
        ROW[i] <- 1
        M[i,] <- ROW
}
b <- rep(0,nsamps_pool1)
IndexOne <- min(which(cumsum(bInclude)==1)) # we have one degree of freedom left, so one equation (for an included sample) can be replaced
M[IndexOne,] <- RUN1/100; b[IndexOne] <- 1  # we want the same total number of molecules as before

FACTOR <- solve(M,b) # solve linear system

# Step 3: compute amount of Tris to add 
volumes_Run2 <- FACTOR*volumes_Run1
tristotal <- volume_pool1 - sum(volumes_Run2)

#################
# Format Output #
#################

Output <- matrix(0,nrow=nsamps_pool1+3,ncol=2)
colnames(Output) <- c("Run1 in ul","Run2 in ul")
rownames(Output) <- c(samples,"Total Lib","Add Tris","Total Pool")
Output[1:nsamps_pool1,1] <- volumes_Run1
Output[1:nsamps_pool1,2] <- volumes_Run2
Output[nsamps_pool1+1,] <- apply(Output[1:nsamps_pool1,],2,sum)
Output[nsamps_pool1+2,2] <- tristotal
Output[nsamps_pool1+3,1] <- volume_pool1
Output[nsamps_pool1+2,1] <- Output[nsamps_pool1+3,1]-Output[nsamps_pool1+1,1]
Output[nsamps_pool1+3,2] <- Output[nsamps_pool1+1,2]+Output[nsamps_pool1+2,2]
Output <- apply(Output,2,round,digits=2)
#Output[nsamps_pool1+4,1] <- ""
#Output[nsamps_pool1+4,2] <- paste("Take ",round(extra_seq,digits=2)," times more volume as before from the pool.",sep="")
Output <- cbind(rownames(Output),Output)
colnames(Output)[1] <- "Sample"

ExcelWorkbook <- createWorkbook()
addWorksheet(ExcelWorkbook,"Repooling",gridLines=FALSE)
writeDataTable(ExcelWorkbook,"Repooling",data.frame(Output),colNames=TRUE)
setColWidths(ExcelWorkbook,"Repooling",cols=1:ncol(Output),widths="auto")
OutFile <- paste("RepoolingInstructions-",format(Sys.time(),format="%Y-%m-%d"),".xlsx",sep="")
saveWorkbook(ExcelWorkbook,OutFile,overwrite=TRUE)
